// src/constants/iconsAndColors.js

export const ioniconsList = [
    { name: 'home-outline' },
    { name: 'cut-sharp' },
    { name: 'archive-outline' },
    { name: 'beer-outline' },
    { name: 'bicycle-outline' },
    { name: 'camera-outline' },
    { name: 'car-outline' },
    { name: 'cart-outline' },
    { name: 'cellular-outline' },
    { name: 'chatbubble-ellipses-outline' },
    { name: 'cloud-outline' },
    { name: 'color-palette-outline' },
    { name: 'document-text-outline' },
    { name: 'flower-outline' },
    { name: 'game-controller-outline' },
    { name: 'gift-outline' },
    { name: 'glasses-outline' },
    { name: 'golf-outline' },
    { name: 'headset-outline' },
    { name: 'ice-cream-outline' },
    { name: 'images-outline' },
    { name: 'key-outline' },
    { name: 'laptop-outline' },
    { name: 'megaphone-outline' },
    { name: 'notifications-outline' },
    { name: 'pizza-outline' },
    { name: 'school-outline' },
    { name: 'shirt-outline' },
    { name: 'trophy-outline' },
    { name: 'videocam-outline' },
  ];
  
  export const colorList = [
    '#fff',
    '#ccc',
    '#F39C12',
    '#FF5733',
    '#33FF57',
    '#3385FF',
    '#FF33A8',
    '#9B59B6',
    '#34495E',
    '#BDC3C7',
    '#E74C3C',
    '#2ECC71',
    '#1ABC9C',
    '#3498DB',
    '#f1c40f',
    '#e67e22',
    '#2c3e50',
    // Agrega más si lo deseas
  ];
  